<a href="https://colab.research.google.com/github/leahkb/Boyle_NEUR265/blob/main/notebooks/numpy_02_10_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In this notebook, we'll encounter a package for scientific computing in Python: NumPy.

**At the end of this notebook, you'll be able to:**
* Install and import packages for Python
* Create NumPy arrays
* Execute methods & access attributes of arrays


## Importing packages

Before we can use numpy, we need to import it. We can also nickname modules when we import them.

The convention is to import `numpy` as `np`.

In [1]:
# Import packages
import numpy as np

# Use whos 'magic command' to see available modules
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/us<...>kages/numpy/__init__.py'>


## Numpy

**Numpy** is the fundamental package for scientific computing with Python. It'll allow us to work with bigger datasets more efficiently.

### Creating `numpy` arrays

A numpy **array** is a grid of values which are all the same type (they’re homogenous).

We can create a numpy array in a few different ways:

* from a Python list or tuples
* by using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, `empty`,`zeroes`, etc.
* reading data from files

In [4]:
# Create a list
lst = [1,2,3,4,5]

# Make our list into an array
my_vector = np.array(lst)
print(type(my_vector))
print(my_vector)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
# If we give numpy a list of lists, it will create a matrix
my_matrix = np.array([lst,lst])
print(my_matrix)

[[1 2 3 4 5]
 [1 2 3 4 5]]


### Accessing attributes of numpy arrays

We can test shape and size either by looking at the attribute of the array, or by using the `shape()` and `size()` methods.

Other attributes that might be of interest are `ndim` and `dtype`.

In [13]:
# Check the type of vector
print("Data type:", my_vector.dtype)

# Check the dimensions of matrix
print("Number of dimensions:", my_matrix.ndim)

#Check the shape
print("Shape:", my_vector.shape)
print("Shape:", my_matrix.shape)


#Check the size
print("Size:", my_vector.size)
print("Size:", my_matrix.size)

Data type: int64
Number of dimensions: 2
Shape: (5,)
Shape: (2, 5)
Size: 5
Size: 10


Array data type is decided upon creation of the array.

You can explicitly define the data type by using `dtype= ` when you use `np.array()`. You can set the dtype to be `int, float, complex, bool, object`, etc

In [15]:
# my_matrix.dtype

my_complex_array = np.array([lst,lst],dtype='complex')
my_complex_array.dtype
print(my_complex_array)

[[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
 [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]]


><b>Task:</b> Create an array of integers called `int_array` that is 2 rows x 3 columns. Access the shape and ndim attributes to confirm its size, and the dtype attribute to confirm that it is indeed an array of integers.



In [17]:
# Your code here
int_array = [ [1, 2, 3], [1, 2, 3]]
int_array = np.array(int_array)
print("Shape:", int_array.shape)
print("Dimensions:", int_array.ndim)

Shape: (2, 3)
Dimensions: 2


### Indexing & slicing arrays

Indexing and slicing 1D arrays (vectors) is similar to indexing lists.

You can index matrices using `[row,column]`. If you omit the column, it will give you the whole row.

If you use `:` for either row or column, it will give you all of those values.

In [29]:
print(my_matrix[0,2])

print(int_array[0][0]) #Testing if this way also works
print(int_array[0,0])
print(int_array[0:2, 0:2]) #Non inclusive


3
1
1
[[1 2]
 [1 2]]


**Booleans** are variables that store `True` or `False`. They are named after the British mathematician George Boole. He first formulated Boolean algebra, which are a set of rules for how to reason with and combine these values. This is the basis of all modern computer logic.

We can also index arrays using Boolean operators or lists. When we use Booleans, we can think of this as filtering the array. For example:

In [62]:
# Index with an operator
bool_matrix = my_matrix[my_matrix>-2]


# Index with a list of coordinates
list_matrix = my_matrix[[0,1],[1,3]]

print(my_matrix)
print(bool_matrix)
print(list_matrix)

#I promise it was 3 4 5 3 4 5 at first, I just was messing with the booleans to get false and changed some stuff

[[-1 -1 -1 -1 -1]
 [ 1  2  3  4  5]]
[-1 -1 -1 -1 -1  1  2  3  4  5]
[-1  4]


><b>Task:</b> Create a variable called `my_boolean_matrix` that is equal to your `bool_matrix` variable, but with `dtype = 'bool'`. Print your `my_boolean_matrix` variable. What happened?




In [63]:
# Your code here
my_boolean_matrix = np.array(bool_matrix, dtype='bool')
print(bool_matrix.dtype, bool_matrix)
print(my_boolean_matrix)

int64 [-1 -1 -1 -1 -1  1  2  3  4  5]
[ True  True  True  True  True  True  True  True  True  True]


We can also change values in an array similar to how we would change values in a list. Run the code below, and then re-run the code with the second line un-commented.

In [64]:
print(my_matrix)
my_matrix[0] = 8

my_matrix[0]
my_matrix[0] = -1
print(my_boolean_matrix)

[[-1 -1 -1 -1 -1]
 [ 1  2  3  4  5]]
[ True  True  True  True  True  True  True  True  True  True]


### Benefits of using arrays

In addition to being less clunky & a bit faster than lists of lists, arrays can do a lot of things that lists can't. For example, we can add and multiply them. Alternatively, we can use the `sum` method to sum across a specific axis.

In [49]:
sum_list = [1,3,5] + [3,5,7] #concatenates
sum_array = np.array([1,3,5]) + np.array([3,5,7]) #sums by column value
mult_array = np.array([1,3,5]) * np.array([3,5,7]) #multiplies by column value

print(sum_list)
print(sum_array)
print(mult_array)

[1, 3, 5, 3, 5, 7]
[ 4  8 12]
[ 3 15 35]


In [72]:
this_array = np.array([[1,3,5],[3,5,7]])
sum_rows = this_array.sum(axis=1)
print(this_array)
print(sum_rows)
sum_rows = this_array.sum(axis=0)
print(sum_rows)


[[1 3 5]
 [3 5 7]]
[ 9 15]
[ 4  8 12]


### Numpy also includes some very useful array generating functions:

* `arange`: like `range` but gives you a useful numpy array, instead of an interator, and can use more than just integers
* `linspace` creates an array with given start and end points, and a desired number of points
* `logspace` same as linspace, but in log.
* `random` can create a random list
* `concatenate` which can concatenate two arrays along an existing axis
* `hstack` and `vstack` which can horizontally or vertically stack arrays

Whenever we call these, we need to use whatever name we imported numpy as (here, `np`).

In [80]:
# When using linspace, both end points are included!
print(np.linspace(0,147,10))

#Range (start, stop, step)
print(np.arange(0,10,2))

#Logspace
print(np.logspace(0,100,20))

#Random
print(np.random.normal()) #normal distribution
print(np.random.randint(0, 100)) # (start, end, size=None)
print(np.random.rand()) # float between 0 and 1

#Concatenate
print(np.concatenate(([1,2,3], [1,2,3]), axis=0, out=None, dtype=None, casting='same_kind' ) )


[  0.          16.33333333  32.66666667  49.          65.33333333
  81.66666667  98.         114.33333333 130.66666667 147.        ]
[0 2 4 6 8]
[1.00000000e+000 1.83298071e+005 3.35981829e+010 6.15848211e+015
 1.12883789e+021 2.06913808e+026 3.79269019e+031 6.95192796e+036
 1.27427499e+042 2.33572147e+047 4.28133240e+052 7.84759970e+057
 1.43844989e+063 2.63665090e+068 4.83293024e+073 8.85866790e+078
 1.62377674e+084 2.97635144e+089 5.45559478e+094 1.00000000e+100]
-0.5306075733153178
11
0.64614803925854
[1 2 3 1 2 3]


>**Task**: Create an array called `big_array` that has two rows. The first row should be a list of 10 numbers that are evenly spaced, and range from exactly 1 to 100. The second row should be a list of 10 numbers that begin at 0 and are exactly 10 apart (*hint*: use [np.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)). `big_array` should have a shape (2,10): two rows, and ten columns. Lastly, reassign the last value of each row in the array to be -100.

In [103]:
# Your code here
r1 = np.array(np.linspace(1,100,10), dtype = 'int')
r2 = np.arange(0,100,10)
big_array = np.array([r1, r2])
print(big_array.shape)
print(big_array)


big_array[0][-1] = -100
big_array[1][-1] = -100

print(big_array)

big_array = big_array[big_array>50]
print(big_array)

(2, 10)
[[  1  12  23  34  45  56  67  78  89 100]
 [  0  10  20  30  40  50  60  70  80  90]]
[[   1   12   23   34   45   56   67   78   89 -100]
 [   0   10   20   30   40   50   60   70   80 -100]]
[56 67 78 89 60 70 80]
